<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createPoi, deletePoi, getAdminPois, updatePoi } from '@/api/pois'
import type { PageResponse, Poi, PoiPayload, PoiType } from '@/types'

const empty=():PoiPayload=>({name:'',type:'ATTRACTION',area:'',address:'',latitude:31.2304,longitude:121.4737,openingHours:'',averagePrice:undefined,ticketPrice:undefined,suggestedDurationMinutes:undefined,description:'',imageUrl:'',rating:undefined,recommended:false,active:true,tags:[]})
const data=ref<PageResponse<Poi>>({items:[],page:0,size:10,totalElements:0,totalPages:0});const loading=ref(false);const error=ref('');const dialog=ref(false);const submitting=ref(false);const deletingId=ref<number>();const editingId=ref<number>();const form=reactive<PoiPayload>(empty());const tagsText=ref('')
const typeLabel=(type:PoiType)=>({ATTRACTION:'景点',RESTAURANT:'美食',BUSINESS_DISTRICT:'商圈'}[type])
const load=async(page=data.value.page)=>{loading.value=true;error.value='';try{data.value=await getAdminPois({page,size:data.value.size})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
const openCreate=()=>{editingId.value=undefined;Object.assign(form,empty());delete form.version;tagsText.value='';dialog.value=true}
const openEdit=(poi:Poi)=>{editingId.value=poi.id;Object.assign(form,{name:poi.name,type:poi.type,area:poi.area,address:poi.address,latitude:poi.latitude,longitude:poi.longitude,openingHours:poi.openingHours,averagePrice:poi.averagePrice,ticketPrice:poi.ticketPrice,suggestedDurationMinutes:poi.suggestedDurationMinutes,description:poi.description,imageUrl:poi.imageUrl,rating:poi.rating,recommended:poi.recommended,active:poi.active,tags:[...poi.tags],version:poi.version});tagsText.value=poi.tags.join(', ');dialog.value=true}
const save=async()=>{if(submitting.value)return;if(!form.name.trim()||!form.area.trim()||!form.address.trim()){ElMessage.warning('请填写名称、区域和地址');return}submitting.value=true;form.tags=tagsText.value.split(/[,，]/).map(v=>v.trim()).filter(Boolean);try{if(editingId.value)await updatePoi(editingId.value,form);else await createPoi(form);dialog.value=false;ElMessage.success(editingId.value?'地点已更新':'地点已创建');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{submitting.value=false}}
const remove=async(poi:Poi)=>{if(deletingId.value)return;if(poi.version===undefined){ElMessage.error('缺少地点版本，请刷新列表后重试');return}try{await ElMessageBox.confirm(`确定停用“${poi.name}”吗？停用后可通过编辑恢复。`,'停用地点',{type:'warning'})}catch{return}deletingId.value=poi.id;try{await deletePoi(poi.id,poi.version);ElMessage.success('地点已停用');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'停用失败')}finally{deletingId.value=undefined}}
onMounted(()=>load(0))
</script>
<template><main class="page"><header><div><h1>地点内容管理</h1><p>维护景点、美食和商圈内容。</p></div><el-button type="primary" @click="openCreate">新建地点</el-button></header><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><el-button text @click="load()">重试</el-button></el-alert><el-table v-loading="loading" :data="data.items" stripe empty-text="暂无地点"><el-table-column prop="name" label="名称" min-width="180"/><el-table-column label="类型" width="90"><template #default="scope">{{typeLabel(scope.row.type)}}</template></el-table-column><el-table-column prop="area" label="区域" width="110"/><el-table-column prop="address" label="地址" min-width="220"/><el-table-column label="状态" width="90"><template #default="scope"><el-tag :type="scope.row.active?'success':'info'">{{scope.row.active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="scope"><el-button text type="primary" @click="openEdit(scope.row)">编辑</el-button><el-button v-if="scope.row.active" text type="danger" :loading="deletingId===scope.row.id" @click="remove(scope.row)">停用</el-button></template></el-table-column></el-table><el-pagination v-if="data.totalPages>1" :current-page="data.page+1" :page-size="data.size" :total="data.totalElements" layout="total, prev, pager, next" @current-change="v=>load(v-1)"/>
<el-dialog v-model="dialog" :title="editingId?'编辑地点':'新建地点'" width="min(760px,95vw)" :close-on-click-modal="!submitting"><el-form label-position="top"><div class="grid"><el-form-item label="名称" required><el-input v-model="form.name" maxlength="120"/></el-form-item><el-form-item label="类型" required><el-select v-model="form.type"><el-option label="景点" value="ATTRACTION"/><el-option label="美食" value="RESTAURANT"/><el-option label="商圈" value="BUSINESS_DISTRICT"/></el-select></el-form-item><el-form-item label="区域" required><el-input v-model="form.area"/></el-form-item><el-form-item label="地址" required><el-input v-model="form.address"/></el-form-item><el-form-item label="经度"><el-input-number v-model="form.longitude" :precision="6" :step="0.001"/></el-form-item><el-form-item label="纬度"><el-input-number v-model="form.latitude" :precision="6" :step="0.001"/></el-form-item><el-form-item label="开放时间"><el-input v-model="form.openingHours"/></el-form-item><el-form-item label="建议游玩（分钟）"><el-input-number v-model="form.suggestedDurationMinutes" :min="1"/></el-form-item><el-form-item label="人均消费"><el-input-number v-model="form.averagePrice" :min="0"/></el-form-item><el-form-item label="门票价格"><el-input-number v-model="form.ticketPrice" :min="0"/></el-form-item><el-form-item label="评分"><el-input-number v-model="form.rating" :min="0" :max="5" :precision="1"/></el-form-item><el-form-item label="标签（逗号分隔）"><el-input v-model="tagsText"/></el-form-item></div><el-form-item label="封面地址"><el-input v-model="form.imageUrl"/></el-form-item><el-form-item label="介绍"><el-input v-model="form.description" type="textarea" :rows="4" maxlength="2000"/></el-form-item><div class="switches"><el-checkbox v-model="form.recommended">推荐</el-checkbox><el-checkbox v-model="form.active">启用</el-checkbox></div></el-form><template #footer><el-button :disabled="submitting" @click="dialog=false">取消</el-button><el-button type="primary" :loading="submitting" @click="save">保存</el-button></template></el-dialog></main></template>
<style scoped>.page{max-width:1200px;margin:0 auto;padding:28px 20px 56px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}header h1{margin:0}header p{color:#909399}.el-table{border-radius:10px}.el-pagination{justify-content:center;margin-top:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.grid :deep(.el-input-number),.grid :deep(.el-select){width:100%}.switches{display:flex;gap:20px}@media(max-width:600px){.grid{grid-template-columns:1fr}}</style>
