<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { addItineraryItem, deleteItineraryItem, getItinerary, updateItinerary, updateItineraryItem } from '@/api/itineraries'
import { getPois } from '@/api/pois'
import type { Itinerary, ItineraryItem, ItineraryItemPayload, ItineraryItemType, ItineraryPayload, Poi, PoiType } from '@/types'
import { inspectSchedule } from '@/utils/itinerary-schedule'
const route=useRoute();const router=useRouter();const id=Number(route.params.id);const validId=Number.isSafeInteger(id)&&id>0;const itinerary=ref<Itinerary|null>(null);const loading=ref(false);const error=ref('');const itemDialog=ref(false);const editingId=ref<number|null>(null)
const planSubmitting=ref(false);const itemSubmitting=ref(false);const deleteSubmittingId=ref<number|null>(null)
const plan=reactive<ItineraryPayload>({title:'',startDate:'',endDate:''})
const blank=():ItineraryItemPayload=>({itemDate:plan.startDate,type:'ATTRACTION',title:'',location:'',notes:'',sortOrder:0})
const item=reactive<ItineraryItemPayload>(blank())
const scheduleIssues=computed(()=>itinerary.value?inspectSchedule(item,itinerary.value,itinerary.value.items,editingId.value):[])
const poiOptions=ref<Poi[]>([]);const poiLoading=ref(false);const poiError=ref('')
const supportsPoi=computed(()=>item.type==='ATTRACTION'||item.type==='RESTAURANT')
const loadPois=async(keyword='')=>{if(!supportsPoi.value)return;poiLoading.value=true;poiError.value='';try{const result=await getPois({type:item.type as PoiType,keyword:keyword||undefined,page:0,size:30});poiOptions.value=result.items}catch(e){poiError.value=e instanceof Error?e.message:'地点加载失败'}finally{poiLoading.value=false}}
const choosePoi=(poiId:number|undefined)=>{const poi=poiOptions.value.find(v=>v.id===poiId);if(!poi)return;item.title=poi.name;item.location=poi.address}
const groups=computed(()=>{const map=new Map<string,ItineraryItem[]>();for(const v of itinerary.value?.items??[]){const list=map.get(v.itemDate)??[];list.push(v);map.set(v.itemDate,list)}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,items])=>({date,dayNumber:items[0]?.dayNumber??1,items}))})
const scheduleIssueMap=computed(()=>{const map=new Map<number,string[]>();if(!itinerary.value)return map;for(const value of itinerary.value.items){const issues=inspectSchedule(value,itinerary.value,itinerary.value.items,value.id);if(issues.length)map.set(value.id,issues.map(issue=>issue.message))}return map})
const acceptMutation=(result:Itinerary)=>{if(!itinerary.value||result.version>itinerary.value.version)itinerary.value=result}
const load=async()=>{if(!validId)return;loading.value=true;error.value='';try{itinerary.value=await getItinerary(id);Object.assign(plan,{title:itinerary.value.title,startDate:itinerary.value.startDate,endDate:itinerary.value.endDate})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
const savePlan=async()=>{if(planSubmitting.value||!itinerary.value)return;planSubmitting.value=true;try{acceptMutation(await updateItinerary(id,itinerary.value.version,plan));ElMessage.success('行程信息已保存')}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{planSubmitting.value=false}}
const openAdd=()=>{editingId.value=null;Object.assign(item,blank());itemDialog.value=true;void loadPois()}
const openEdit=(value:ItineraryItem)=>{editingId.value=value.id;Object.assign(item,{itemDate:value.itemDate,type:value.type,startTime:value.startTime,endTime:value.endTime,title:value.title,location:value.location,notes:value.notes,sortOrder:value.sortOrder,hotelId:value.hotelId,poiId:value.poiId});itemDialog.value=true;if(value.type==='ATTRACTION'||value.type==='RESTAURANT')void loadPois()}
const saveItem=async()=>{if(itemSubmitting.value||!itinerary.value)return;if(scheduleIssues.value.length){ElMessage.warning('请先解决时间安排问题');return}itemSubmitting.value=true;try{const version=itinerary.value.version;const result=editingId.value?await updateItineraryItem(id,editingId.value,version,item):await addItineraryItem(id,version,item);acceptMutation(result);itemDialog.value=false;ElMessage.success('项目已保存')}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{itemSubmitting.value=false}}
const removeItem=async(value:ItineraryItem)=>{if(deleteSubmittingId.value!==null||!itinerary.value)return;try{await ElMessageBox.confirm(`删除项目“${value.title}”？`,'删除项目')}catch{return}deleteSubmittingId.value=value.id;try{acceptMutation(await deleteItineraryItem(id,value.id,itinerary.value.version))}catch(e){ElMessage.error(e instanceof Error?e.message:'删除失败')}finally{deleteSubmittingId.value=null}}
const typeLabel=(type:ItineraryItemType)=>({HOTEL:'酒店',ATTRACTION:'景点',RESTAURANT:'餐厅',ACTIVITY:'活动',NOTE:'备注'}[type])
watch(()=>item.type,()=>{if(!supportsPoi.value){item.poiId=undefined;poiOptions.value=[];poiError.value=''}else void loadPois()})
onMounted(()=>{if(!validId){ElMessage.error('行程编号不正确');void router.replace('/itineraries');return}void load()})
</script>
<template><main class="page" v-loading="loading"><el-button text @click="router.push('/itineraries')">← 返回行程列表</el-button><el-alert v-if="error" :title="error" type="error" show-icon><el-button text @click="load">重试</el-button></el-alert>
<template v-if="itinerary"><el-card class="plan"><div class="plan-form"><el-input v-model="plan.title" maxlength="100"/><el-date-picker v-model="plan.startDate" type="date" value-format="YYYY-MM-DD"/><span>至</span><el-date-picker v-model="plan.endDate" type="date" value-format="YYYY-MM-DD"/><el-button type="primary" :loading="planSubmitting" :disabled="planSubmitting||itemSubmitting||deleteSubmittingId!==null" @click="savePlan">保存行程</el-button></div></el-card>
<div class="toolbar"><h2>行程项目</h2><el-button type="primary" :disabled="planSubmitting||itemSubmitting||deleteSubmittingId!==null" @click="openAdd">添加项目</el-button></div><el-empty v-if="!itinerary.items.length" description="还没有项目，请手动添加"/>
<section v-for="group in groups" :key="group.date" class="day"><h3>第 {{group.dayNumber}} 天 · {{group.date}}</h3><el-card v-for="value in group.items" :key="value.id" shadow="never" class="item"><div><el-tag>{{typeLabel(value.type)}}</el-tag><el-tag v-if="value.poiId&&value.poiActive===false" type="danger" class="inactive-poi">地点已停用</el-tag><strong>{{value.startTime?.slice(0,5)||'待定'}} {{value.title}}</strong><p>{{value.location||'未填写地点'}}<span v-if="value.hotelName"> · {{value.hotelName}}</span><span v-if="value.poiName"> · 已关联 {{value.poiName}}</span></p><p v-for="issue in scheduleIssueMap.get(value.id) ?? []" :key="issue" class="schedule-issue">⚠ {{issue}}</p><small v-if="value.notes">{{value.notes}}</small></div><div><el-button text type="primary" :disabled="itemSubmitting||deleteSubmittingId!==null" @click="openEdit(value)">编辑</el-button><el-button text type="danger" :loading="deleteSubmittingId===value.id" :disabled="itemSubmitting||deleteSubmittingId!==null" @click="removeItem(value)">删除</el-button></div></el-card></section></template>
<el-dialog v-model="itemDialog" :title="editingId?'编辑项目':'添加项目'" width="min(560px, 94vw)"><el-form label-position="top"><div class="row"><el-form-item label="日期" required><el-date-picker v-model="item.itemDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="类型" required><el-select v-model="item.type"><el-option label="酒店" value="HOTEL"/><el-option label="景点" value="ATTRACTION"/><el-option label="餐厅" value="RESTAURANT"/><el-option label="活动" value="ACTIVITY"/><el-option label="备注" value="NOTE"/></el-select></el-form-item></div><el-form-item v-if="supportsPoi" label="关联数据库地点（可选）" :error="poiError"><el-select v-model="item.poiId" clearable filterable remote :remote-method="loadPois" :loading="poiLoading" placeholder="可选择地点，也可继续手动填写" @change="choosePoi"><el-option v-for="poi in poiOptions" :key="poi.id" :label="`${poi.name} · ${poi.area}`" :value="poi.id"/></el-select></el-form-item><el-form-item label="标题" required><el-input v-model="item.title" maxlength="120"/></el-form-item><div class="row"><el-form-item label="开始时间"><el-time-picker v-model="item.startTime" value-format="HH:mm:ss" format="HH:mm"/></el-form-item><el-form-item label="结束时间"><el-time-picker v-model="item.endTime" value-format="HH:mm:ss" format="HH:mm"/></el-form-item><el-form-item label="排序"><el-input-number v-model="item.sortOrder" :min="0" :max="10000"/></el-form-item></div><el-alert v-if="scheduleIssues.length" title="时间安排需调整" type="warning" :closable="false" show-icon class="schedule-alert"><p v-for="(issue, index) in scheduleIssues" :key="`${issue.code}-${issue.conflictingItemId ?? index}`">{{ issue.message }}</p></el-alert><el-form-item label="地点"><el-input v-model="item.location" maxlength="200"/></el-form-item><el-form-item label="备注"><el-input v-model="item.notes" type="textarea" maxlength="2000"/></el-form-item><el-form-item label="关联酒店编号（可选）"><el-input-number v-model="item.hotelId" :min="1"/></el-form-item></el-form><template #footer><el-button :disabled="itemSubmitting" @click="itemDialog=false">取消</el-button><el-button type="primary" :loading="itemSubmitting" :disabled="itemSubmitting || scheduleIssues.length > 0" @click="saveItem">保存</el-button></template></el-dialog></main></template>
<style scoped>.page{max-width:1000px;margin:20px auto;padding:0 16px}.plan{margin:16px 0}.plan-form{display:flex;gap:10px;align-items:center}.toolbar{display:flex;justify-content:space-between;align-items:center;margin:24px 0 12px}.day{margin-bottom:20px}.day h3{margin-bottom:10px}.item{margin-bottom:8px}.item :deep(.el-card__body){display:flex;justify-content:space-between;align-items:flex-start}.item strong{margin-left:10px}.inactive-poi{margin-left:8px}.item p,.item small{display:block;color:#909399;margin:8px 0 0}.item .schedule-issue{color:#b95b00}.schedule-alert{margin-bottom:16px}.schedule-alert p{margin:4px 0}.row{display:flex;gap:12px}.row>*{flex:1}@media(max-width:700px){.plan-form,.row{flex-direction:column;align-items:stretch}.item :deep(.el-card__body){flex-direction:column;gap:10px}}</style>
