<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getPoi } from '@/api/pois'
import PoiCoordinatePlot from '@/components/PoiCoordinatePlot.vue'
import type { Poi, PoiType } from '@/types'
const route=useRoute();const router=useRouter();const poi=ref<Poi>();const loading=ref(false);const error=ref('')
const id=computed(()=>Number(route.params.id));const typeLabel=(type:PoiType)=>({ATTRACTION:'景点',RESTAURANT:'美食',BUSINESS_DISTRICT:'商圈'}[type])
const load=async()=>{if(!Number.isSafeInteger(id.value)||id.value<1){error.value='地点编号不正确';return}loading.value=true;error.value='';try{poi.value=await getPoi(id.value)}catch(e){error.value=e instanceof Error?e.message:'地点加载失败'}finally{loading.value=false}}
onMounted(load)
</script>
<template><main class="page" v-loading="loading"><el-button text @click="router.push('/pois')">← 返回地点列表</el-button><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><el-button text @click="load">重试</el-button></el-alert><template v-if="poi"><section class="cover"><img :src="poi.imageUrl||'/images/banner-2.jpg'" :alt="poi.name"/><div><el-tag>{{typeLabel(poi.type)}}</el-tag><h1>{{poi.name}}</h1><p>{{poi.area}} · {{poi.address}}</p><div class="tags"><el-tag v-for="tag in poi.tags" :key="tag" type="warning" effect="plain">{{tag}}</el-tag></div></div></section><el-descriptions title="地点信息" :column="2" border><el-descriptions-item label="开放时间">{{poi.openingHours||'暂无'}}</el-descriptions-item><el-descriptions-item label="评分">{{poi.rating??'暂无'}}</el-descriptions-item><el-descriptions-item label="人均消费">{{poi.averagePrice!==undefined?`￥${poi.averagePrice}`:'暂无'}}</el-descriptions-item><el-descriptions-item label="门票价格">{{poi.ticketPrice!==undefined?`￥${poi.ticketPrice}`:(poi.price!==undefined?`￥${poi.price}`:'暂无')}}</el-descriptions-item><el-descriptions-item label="建议游玩">{{poi.suggestedDurationMinutes?`${poi.suggestedDurationMinutes} 分钟`:'暂无'}}</el-descriptions-item><el-descriptions-item label="坐标">{{poi.longitude}}, {{poi.latitude}}</el-descriptions-item><el-descriptions-item label="介绍" :span="2">{{poi.description||'暂无介绍'}}</el-descriptions-item></el-descriptions><PoiCoordinatePlot class="plot" :pois="[poi]" :selected-id="poi.id"/></template></main></template>
<style scoped>.page{max-width:1000px;margin:0 auto;padding:24px 20px 56px}.cover{display:grid;grid-template-columns:minmax(300px,48%) 1fr;gap:28px;align-items:center;margin:20px 0 28px}.cover img{width:100%;height:310px;object-fit:cover;border-radius:14px}.cover h1{font-size:36px;margin:14px 0}.cover p{color:#606266}.tags{display:flex;gap:8px;flex-wrap:wrap}.plot{margin-top:24px}@media(max-width:640px){.cover{grid-template-columns:1fr}.cover img{height:230px}:deep(.el-descriptions__body .el-descriptions__table){font-size:12px}}</style>
