<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Search } from '@element-plus/icons-vue'
import { getPois } from '@/api/pois'
import PoiCoordinatePlot from '@/components/PoiCoordinatePlot.vue'
import type { Poi, PoiQuery, PoiType } from '@/types'

const route=useRoute();const router=useRouter()
const filters=reactive<PoiQuery>({keyword:String(route.query.keyword||''),type:(route.query.type as PoiType)||undefined,area:String(route.query.area||''),page:Math.max(0,Number(route.query.page)||0),size:9})
const page=ref({items:[] as Poi[],page:0,size:9,totalElements:0,totalPages:0});const loading=ref(false);const error=ref('');const selectedId=ref<number>()
const areas=computed(()=>Array.from(new Set(page.value.items.map(v=>v.area).filter(Boolean))))
const typeLabel=(type:PoiType)=>({ATTRACTION:'景点',RESTAURANT:'美食',BUSINESS_DISTRICT:'商圈'}[type])
const price=(poi:Poi)=>poi.ticketPrice??poi.averagePrice??poi.price
const load=async()=>{loading.value=true;error.value='';try{page.value=await getPois(filters);selectedId.value=page.value.items[0]?.id;await router.replace({query:{...(filters.keyword&&{keyword:filters.keyword}),...(filters.type&&{type:filters.type}),...(filters.area&&{area:filters.area}),...(filters.page&&{page:String(filters.page)})}})}catch(e){error.value=e instanceof Error?e.message:'地点加载失败'}finally{loading.value=false}}
const search=()=>{filters.page=0;void load()};const changePage=(value:number)=>{filters.page=value-1;void load()}
const choose=(poi:Poi)=>{selectedId.value=poi.id}
onMounted(load)
</script>
<template><main class="page"><header class="hero"><div><span class="eyebrow">EXPLORE SHANGHAI</span><h1>探索上海</h1><p>从景点、美食到商圈，用真实地点数据规划下一站。</p></div><el-button @click="router.push('/')">返回首页</el-button></header>
<el-card class="filters"><el-input v-model="filters.keyword" clearable placeholder="搜索地点名称或介绍" :prefix-icon="Search" @keyup.enter="search"/><el-select v-model="filters.type" clearable placeholder="全部类型"><el-option label="景点" value="ATTRACTION"/><el-option label="美食" value="RESTAURANT"/><el-option label="商圈" value="BUSINESS_DISTRICT"/></el-select><el-select v-model="filters.area" clearable filterable allow-create placeholder="全部区域"><el-option v-for="area in areas" :key="area" :label="area" :value="area"/></el-select><el-button type="primary" :loading="loading" @click="search">搜索</el-button></el-card>
<el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><el-button text @click="load">重试</el-button></el-alert>
<section v-loading="loading" class="content"><template v-if="page.items.length"><div class="cards"><article v-for="poi in page.items" :key="poi.id" class="card" :class="{selected:poi.id===selectedId}" @mouseenter="choose(poi)" @click="router.push(`/pois/${poi.id}`)"><img :src="poi.imageUrl||'/images/banner-2.jpg'" :alt="poi.name"/><div class="body"><div class="title"><h2>{{poi.name}}</h2><el-tag size="small">{{typeLabel(poi.type)}}</el-tag></div><p class="address">{{poi.area}} · {{poi.address}}</p><p class="desc">{{poi.description||'暂无介绍'}}</p><div class="meta"><span v-if="price(poi)!==undefined">参考价 ￥{{price(poi)}}</span><span v-if="poi.rating">评分 {{poi.rating}}</span></div></div></article></div><PoiCoordinatePlot :pois="page.items" :selected-id="selectedId" @select="choose"/><el-pagination v-if="page.totalPages>1" :current-page="page.page+1" :page-size="page.size" :total="page.totalElements" layout="total, prev, pager, next" @current-change="changePage"/></template><el-empty v-else-if="!loading&&!error" description="没有找到符合条件的地点"><el-button @click="Object.assign(filters,{keyword:'',type:undefined,area:'',page:0});load()">清空筛选</el-button></el-empty></section></main></template>
<style scoped>.page{max-width:1200px;margin:0 auto;padding:28px 20px 56px}.hero{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:22px}.hero h1{font-size:36px;margin:4px 0}.hero p{color:#606266}.eyebrow{color:#409eff;font-size:12px;letter-spacing:2px}.filters :deep(.el-card__body){display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:12px}.content{min-height:240px;margin-top:18px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px}.card{border:1px solid #ebeef5;border-radius:12px;overflow:hidden;background:#fff;cursor:pointer;transition:.2s}.card:hover,.card.selected{border-color:#409eff;transform:translateY(-2px);box-shadow:0 8px 24px rgba(31,45,61,.11)}.card img{width:100%;height:170px;object-fit:cover}.body{padding:14px}.title{display:flex;justify-content:space-between;align-items:center;gap:8px}.title h2{font-size:18px;margin:0}.address,.desc{color:#606266;font-size:13px}.desc{height:40px;overflow:hidden}.meta{display:flex;justify-content:space-between;color:#f56c6c;font-weight:600}.el-pagination{justify-content:center;margin-top:24px}@media(max-width:820px){.filters :deep(.el-card__body){grid-template-columns:1fr 1fr}.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.hero{display:block}.filters :deep(.el-card__body),.cards{grid-template-columns:1fr}}</style>
