import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'
import { DatabaseService } from '../database/database.service'
import { asSafeNumber } from '../common/json-codec'

type Plan = {title:string;startDate:string;endDate:string}; type Item = {itemDate:string;type:string;startTime?:string;endTime?:string;title:string;location?:string;notes?:string;sortOrder:number;hotelId?:number;poiId?:number}
const detail = { itinerary_items: { include: { hotels: { select: { id:true,name:true } }, pois: { select: { id:true,name:true,active:true,type:true } } }, orderBy: [{ item_date:'asc' as const },{ sort_order:'asc' as const },{ id:'asc' as const }] } }

@Injectable()
export class ItinerariesService {
  constructor(private readonly db:DatabaseService){}
  async list(user:bigint){const rows=await this.db.itineraries.findMany({where:{user_id:user},orderBy:{updated_at:'desc'}});return rows.map((x)=>planResponse(x,[]))}
  async get(user:bigint,id:number){return planResponse(await this.require(user,id),undefined)}
  async create(user:bigint,p:Plan){validatePlan(p);const now=new Date();const row=await this.db.itineraries.create({data:{user_id:user,title:p.title.trim(),start_date:day(p.startDate),end_date:day(p.endDate),created_at:now,updated_at:now}});return planResponse(row,[])}
  async update(user:bigint,id:number,h:string|undefined,p:Plan){validatePlan(p);const old=await this.require(user,id);checkVersion(old,h);if(old.itinerary_items.some((x:any)=>dateText(x.item_date)<p.startDate||dateText(x.item_date)>p.endDate))throw new BadRequestException('新的行程日期范围会使已有项目越界，请先调整或删除项目');const changed=await this.db.$transaction(async tx=>{const result=await tx.itineraries.updateMany({where:{id:old.id,user_id:user,version:old.version},data:{title:p.title.trim(),start_date:day(p.startDate),end_date:day(p.endDate),updated_at:nextTime(old.updated_at),version:{increment:1}}});if(result.count!==1)throw new ConflictException('行程已被更新，请刷新后重试');for(const item of old.itinerary_items)await tx.itinerary_items.update({where:{id:item.id},data:{day_number:dayNo(p.startDate,dateText(item.item_date))}});return tx.itineraries.findFirstOrThrow({where:{id:old.id,user_id:user},include:detail})});return planResponse(changed,undefined)}
  async remove(user:bigint,id:number,h:string|undefined){const old=await this.require(user,id);checkVersion(old,h);const result=await this.db.itineraries.deleteMany({where:{id:old.id,user_id:user,version:old.version}});if(result.count!==1)throw new ConflictException('行程已被更新，请刷新后重试')}
  async addItem(user:bigint,id:number,h:string|undefined,item:Item){const old=await this.require(user,id);checkVersion(old,h);await this.validateItem(old,item);await this.db.$transaction(async tx=>{const bumped=await tx.itineraries.updateMany({where:{id:old.id,user_id:user,version:old.version},data:{updated_at:nextTime(old.updated_at),version:{increment:1}}});if(!bumped.count)throw new ConflictException('行程已被更新，请刷新后重试');await tx.itinerary_items.create({data:itemData(old,item)})});return this.get(user,id)}
  async updateItem(user:bigint,id:number,itemId:number,h:string|undefined,item:Item){const old=await this.require(user,id);checkVersion(old,h);if(!old.itinerary_items.some((x:any)=>x.id===BigInt(itemId)))throw new NotFoundException('行程项目不存在');await this.validateItem(old,item);await this.db.$transaction(async tx=>{const bumped=await tx.itineraries.updateMany({where:{id:old.id,user_id:user,version:old.version},data:{updated_at:nextTime(old.updated_at),version:{increment:1}}});if(!bumped.count)throw new ConflictException('行程已被更新，请刷新后重试');await tx.itinerary_items.update({where:{id:BigInt(itemId)},data:itemData(old,item)})});return this.get(user,id)}
  async deleteItem(user:bigint,id:number,itemId:number,h:string|undefined){const old=await this.require(user,id);checkVersion(old,h);await this.db.$transaction(async tx=>{const bumped=await tx.itineraries.updateMany({where:{id:old.id,user_id:user,version:old.version},data:{updated_at:nextTime(old.updated_at),version:{increment:1}}});if(!bumped.count)throw new ConflictException('行程已被更新，请刷新后重试');const deleted=await tx.itinerary_items.deleteMany({where:{id:BigInt(itemId),itinerary_id:old.id}});if(!deleted.count)throw new NotFoundException('行程项目不存在')});return this.get(user,id)}
  private async require(user:bigint,id:number):Promise<any>{const row=await this.db.itineraries.findFirst({where:{id:BigInt(id),user_id:user},include:detail});if(!row)throw new NotFoundException('行程不存在');return row}
  private async validateItem(plan:any,item:Item){if(!item.title.trim())throw new BadRequestException('项目标题不能为空白');if(!validDay(item.itemDate)||item.itemDate<dateText(plan.start_date)||item.itemDate>dateText(plan.end_date))throw new BadRequestException('项目日期必须在行程范围内');if(Boolean(item.startTime)!==Boolean(item.endTime))throw new BadRequestException('开始时间和结束时间必须同时填写或同时留空');if(item.startTime&&item.endTime){const start=timeSeconds(item.startTime),end=timeSeconds(item.endTime);if(start===null||end===null)throw new BadRequestException('时间格式无效');if(end<=start)throw new BadRequestException('结束时间必须晚于开始时间')}if(item.hotelId&&item.poiId)throw new BadRequestException('酒店和 POI 不能同时关联');if(item.hotelId&&item.type!=='HOTEL')throw new BadRequestException('hotelId 只能用于 HOTEL 类型项目');if(item.poiId){if(!['ATTRACTION','RESTAURANT'].includes(item.type))throw new BadRequestException('poiId 只能用于 ATTRACTION 或 RESTAURANT 类型项目');const poi=await this.db.pois.findFirst({where:{id:BigInt(item.poiId),active:true}});if(!poi)throw new NotFoundException('关联 POI 不存在');if(poi.type!==item.type)throw new BadRequestException('POI 类型与行程项目类型不匹配')}if(item.hotelId&&!await this.db.hotels.findUnique({where:{id:BigInt(item.hotelId)}}))throw new NotFoundException('关联酒店不存在')}
}
export function validatePlan(p:Plan){if(!p.title.trim())throw new BadRequestException('行程标题不能为空白');if(!validDay(p.startDate)||!validDay(p.endDate)||p.endDate<p.startDate)throw new BadRequestException('行程结束日期不能早于开始日期');if(days(p.startDate,p.endDate)>30)throw new BadRequestException('单个行程最多31天')}
function itemData(p:any,x:Item):any{return {itinerary_id:p.id,item_date:day(x.itemDate),day_number:dayNo(dateText(p.start_date),x.itemDate),type:x.type,start_time:x.startTime?time(x.startTime):null,end_time:x.endTime?time(x.endTime):null,title:x.title.trim(),location:x.location?.trim()||null,notes:x.notes?.trim()||null,sort_order:x.sortOrder,hotel_id:x.hotelId?BigInt(x.hotelId):null,poi_id:x.poiId?BigInt(x.poiId):null}}
function planResponse(p:any,items:any[]|undefined){return {id:asSafeNumber(p.id),version:asSafeNumber(p.version),title:p.title,startDate:dateText(p.start_date),endDate:dateText(p.end_date),createdAt:p.created_at.toISOString(),updatedAt:p.updated_at.toISOString(),items:items??p.itinerary_items.map(itemResponse)}}
function itemResponse(x:any){return {id:asSafeNumber(x.id),itemDate:dateText(x.item_date),dayNumber:x.day_number,type:x.type,startTime:x.start_time?x.start_time.toISOString().slice(11,19):null,endTime:x.end_time?x.end_time.toISOString().slice(11,19):null,title:x.title,location:x.location,notes:x.notes,sortOrder:x.sort_order,hotelId:x.hotel_id?asSafeNumber(x.hotel_id):null,hotelName:x.hotels?.name??null,poiId:x.poi_id?asSafeNumber(x.poi_id):null,poiName:x.pois?.name??null,poiActive:x.pois?.active??null}}
function checkVersion(p:any,h:string|undefined){const m=h?.trim().match(/^(?:W\/)?"([0-9]+)"$|^([0-9]+)$/);if(!m)throw new BadRequestException('If-Match 必须是非负版本号');if(p.version!==BigInt(m[1]??m[2]))throw new ConflictException('行程已被更新，请刷新后重试')}
function day(s:string){return new Date(s+'T00:00:00.000Z')} function time(s:string){return new Date('1970-01-01T'+(s.length===5?s+':00':s)+'Z')} function dateText(d:Date){return d.toISOString().slice(0,10)} function validDay(s:string){const value=day(s);return /^\d{4}-\d{2}-\d{2}$/.test(s)&&s>='1000-01-01'&&!Number.isNaN(value.valueOf())&&dateText(value)===s} function days(a:string,b:string){return Math.round((day(b).valueOf()-day(a).valueOf())/86400000)} function dayNo(a:string,b:string){return days(a,b)+1} function nextTime(old:Date){const n=new Date();return n>old?n:new Date(old.valueOf()+1)}
function timeSeconds(s:string):number|null{const m=/^([01]\d|2[0-3]):([0-5]\d)(?::([0-5]\d))?$/.exec(s);return m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]??0):null}
